#ゲーム名
plugin:
  name: "人狼RPG"

#人狼チャットと霊界チャットの表示名と利用可能かどうか
chat:
  spiritworld:
    allow: true
    name: "霊界チャット"
  jinro:
    allow: true
    name: "人狼チャット"

#ゲーム内ショップの表示名と地雷を買えるかどうか
shop:
  name: "店員"
  allow:
    mine: true

#強盗を使用するか
role:
  enable:
    robbery: true

#スケルトンの設定
skeleton:
  spawnticks: 5
  health: 2.0
  equipment: false

#時間
times:
  day:
    name: "DAY TIME"
    message: "昼になりました"
    seconds: 100
  night:
    name: "NIGHT TIME"
    message: "夜になりました"
    seconds: 100

allowbeacon: true