#ゲーム名
plugin:
  name: "人狼RPG"

#霊界チャットの表示名と利用可能かどうか
chat:
  spiritworld:
    allow: true
    name: "霊界チャット"

#ゲーム内ショップの表示名
shop:
  name: "店員"

#スケルトンの設定
skeleton:
  spawnticks: 5
  health: 2.0
  equipment: false
  dropchance: 2 #dropchance分の1の確率でドロップします

#時間
times:
  day:
    name: "DAY TIME"
    message: "昼になりました"
    seconds: 100
  night:
    name: "NIGHT TIME"
    message: "夜になりました"
    seconds: 100